In [73]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [62]:
df=pd.read_csv('https://breathecode.herokuapp.com/asset/internal-link?id=929&path=medical_insurance_cost.csv')

In [63]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

# Valores unicos

In [64]:
valores_unicos=df.nunique()
valores_unicos

age           47
sex            2
bmi          548
children       6
smoker         2
region         4
charges     1337
dtype: int64

# Filas y columnas duplicadas

In [65]:
df.duplicated().sum()

np.int64(1)

In [66]:

df_duplicadas=df[df.duplicated()]
df_duplicadas

     age   sex    bmi  children smoker     region    charges
581   19  male  30.59         0     no  northwest  1639.5631

In [67]:
# Eliminamos fila diplicada
df=df.drop_duplicates()

In [68]:
df.T.duplicated().sum()

np.int64(0)

# Valores faltantes

In [69]:
promedio_faltantes=df.isna().mean()*100
faltantes = ["no hay valores faltantes"] if any(n == 0 for n in promedio_faltantes) else promedio_faltantes
faltantes

['no hay valores faltantes']

# Codificar variables categoricas

In [70]:
columns=df.select_dtypes(include=['object', 'category']).columns.tolist()
df_dummies=pd.get_dummies(df[columns], drop_first=True, dtype=int)
num_cols = df.select_dtypes(exclude=['object', 'category'])
df=pd.concat([df_dummies,num_cols],axis=1)

In [71]:
df

,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest,age,bmi,children,charges
0,0,1,0,0,1,19,27.900,0,16884.92400
1,1,0,0,1,0,18,33.770,1,1725.55230
2,1,0,0,1,0,28,33.000,3,4449.46200
3,1,0,1,0,0,33,22.705,0,21984.47061
4,1,0,1,0,0,32,28.880,0,3866.85520
...,...,...,...,...,...,...,...,...,...
1333,1,0,1,0,0,50,30.970,3,10600.54830
1334,0,0,0,0,0,18,31.920,0,2205.98080
1335,0,0,0,1,0,18,36.850,0,1629.83350
1336,0,0,0,0,1,21,25.800,0,2007.94500
1337,0,1,1,0,0,61,29.070,0,29141.36030

# Train test split

In [74]:
X= df.drop('charges',axis=1)
y= df['charges']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [75]:
pd.set_option('display.float_format', '{:.3f}'.format)
X_train.describe().T

                    count   mean    std    min    25%    50%    75%    max
sex_male         1069.000  0.514  0.500  0.000  0.000  1.000  1.000  1.000
smoker_yes       1069.000  0.200  0.400  0.000  0.000  0.000  0.000  1.000
region_northwest 1069.000  0.247  0.431  0.000  0.000  0.000  0.000  1.000
region_southeast 1069.000  0.268  0.443  0.000  0.000  0.000  1.000  1.000
region_southwest 1069.000  0.248  0.432  0.000  0.000  0.000  0.000  1.000
age              1069.000 39.198 13.999 18.000 27.000 39.000 51.000 64.000
bmi              1069.000 30.540  6.052 15.960 26.180 30.200 34.430 53.130
children         1069.000  1.084  1.195  0.000  0.000  1.000  2.000  5.000